[build]
  cmd = "go build -o ./tmp/main ./cmd/local"
  bin = "./tmp/main"
  dir = "."
  include_ext = ["go", "tpl", "html"]
  exclude_dir = ["vendor", "assets", "tmp"]
  run_after_build = "chmod +x ./main"
  poll = true
  poll_interval = 500

[log]
  level = "debug"