name: pos-dev
services:
  backend:
    image: cosmtrek/air:v1.65.3
    container_name: pos-backend-dev
    ports:
      - "${PORT}:8080"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - PORT=${PORT}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - JWT_SECRET=${JWT_SECRET}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - pos-dev-net

  postgres:
    image: postgres:18-alpine
    container_name: pos-db-dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped
    networks:
      - pos-dev-net

volumes:
  postgres_data:

networks:
  pos-dev-net:
    external: true
